name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build code
      run: cargo build --verbose
    - name: Build docs
      run: cargo doc --no-deps
    - name: Run tests
      run: cargo test --verbose
